### ISSUE TITLE
Problem: Spring Boot BOM does override versions of jakarta valdation and Hibernate validator

### ISSUE THREAD

**Issue by jonathanlukas** [camunda-community-hub/spring-zeebe#256]
When using the spring-boot-dependencies as BOM (version 2.7.5), the Jakarta Validation API will be pulled in version 2.0.2.

This results in another package name (javax.validation) than the version 3.x (jakarta.validation) used by camunda connector-validation.

As result, you will get a `ServiceConfigurationError` like this:
```
java.util.ServiceConfigurationError: io.camunda.connector.api.validation.ValidationProvider: io.camunda.connector.validation.impl.DefaultValidationProvider Unable to get public no-arg constructor
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586) ~[na:na]
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:679) ~[na:na]
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1240) ~[na:na]
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273) ~[na:na]
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309) ~[na:na]
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393) ~[na:na]
	at java.base/java.util.ServiceLoader.findFirst(ServiceLoader.java:1811) ~[na:na]
	at io.camunda.connector.impl.outbound.AbstractOutboundConnectorContext.getValidationProvider(AbstractOutboundConnectorContext.java:53) ~[connector-core-0.3.0-alpha1.jar:0.3.0-alpha1]
	at io.camunda.connector.impl.outbound.AbstractOutboundConnectorContext.validate(AbstractOutboundConnectorContext.java:30) ~[connector-core-0.3.0-alpha1.jar:0.3.0-alpha1]
	at io.camunda.connector.jira.JiraFunction.execute(JiraFunction.java:22) ~[classes/:na]
	at io.camunda.zeebe.spring.client.jobhandling.JobHandlerInvokingSpringBeans.handle(JobHandlerInvokingSpringBeans.java:71) ~[spring-zeebe-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44) ~[zeebe-client-java-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39) ~[zeebe-client-java-8.1.2.jar:8.1.2]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.lang.NoClassDefFoundError: jakarta/validation/ValidationException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[na:na]
	at java.base/java.lang.Class.getConstructor0(Class.java:3578) ~[na:na]
	at java.base/java.lang.Class.getConstructor(Class.java:2271) ~[na:na]
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:666) ~[na:na]
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:663) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569) ~[na:na]
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:674) ~[na:na]
	... 18 common frames omitted
Caused by: java.lang.ClassNotFoundException: jakarta.validation.ValidationException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 26 common frames omitted
```
As it is an `Error` and not an `Exception`, it will never be handled or logged.

As a simple workaround, you could catch `Throwable` on invocation of a connector function.

**Comment by tmetzke** [comment]
Should be solved with https://github.com/camunda/connector-sdk/pull/248.

**Note**: This requires ALL Connectors to adjust their validation annotations from `jakarta.validation.*` to `javax.validation`.
