### ISSUE TITLE
Connect to SaaS using provided env vars

### ISSUE THREAD

**Issue by korthout** [camunda-community-hub/spring-zeebe#284]
When creating a new [SaaS API client](https://docs.camunda.io/docs/components/console/manage-clusters/manage-api-clients/), I can choose between Spring Boot and Environment Variables (Env Vars). I run `spring-zeebe` in a Docker container and configure it using env vars. To do this, I need to manually transform the Spring Boot configuration properties into environment variables because the Env Vars credentials provided by Console cannot be used directly in spring-zeebe.

It would be much easier for me to use the downloaded Env Vars credentials directly in spring-zeebe.

Example, using the downloaded Env Vars from the newly created SaaS API Client:
```
ZEEBE_ADDRESS='<my-cluster-id>.bru-2.zeebe.camunda.io:443'
ZEEBE_CLIENT_ID='<my-client-id>'
ZEEBE_CLIENT_SECRET='<my-client-secret>'
ZEEBE_AUTHORIZATION_SERVER_URL='https://login.cloud.camunda.io/oauth/token'
ZEEBE_TOKEN_AUDIENCE='zeebe.camunda.io'
CAMUNDA_CLUSTER_ID='<my-cluster-id>'
CAMUNDA_CLUSTER_REGION='bru-2'
CAMUNDA_CREDENTIALS_SCOPES='Zeebe'
CAMUNDA_OAUTH_URL='https://login.cloud.camunda.io/oauth/token'
```

I run into the following error at startup:

```
2022-12-04 10:46:35.015 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'zeebeClientLifecycle'; nested exception is java.lang.IllegalArgumentException: java.net.MalformedURLException: no protocol: 'https://login.cloud.camunda.io/oauth/token'
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.23.jar:5.3.23]
	at java.base/java.lang.Iterable.forEach(Unknown Source) ~[na:na]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.4.jar:2.7.4]
	at com.github.korthout.zeeberestclient.ZeebeRestClientApplicationKt.main(ZeebeRestClientApplication.kt:13) ~[classes/:na]
Caused by: java.lang.IllegalArgumentException: java.net.MalformedURLException: no protocol: 'https://login.cloud.camunda.io/oauth/token'
	at io.camunda.zeebe.client.impl.oauth.OAuthCredentialsProviderBuilder.validate(OAuthCredentialsProviderBuilder.java:238) ~[zeebe-client-java-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.client.impl.oauth.OAuthCredentialsProviderBuilder.build(OAuthCredentialsProviderBuilder.java:157) ~[zeebe-client-java-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.client.impl.ZeebeClientBuilderImpl.createDefaultCredentialsProvider(ZeebeClientBuilderImpl.java:375) ~[zeebe-client-java-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.client.impl.ZeebeClientBuilderImpl.applyOverrides(ZeebeClientBuilderImpl.java:339) ~[zeebe-client-java-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.client.impl.ZeebeClientBuilderImpl.build(ZeebeClientBuilderImpl.java:311) ~[zeebe-client-java-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.spring.client.ZeebeClientSpringConfiguration$1.getObject(ZeebeClientSpringConfiguration.java:39) ~[spring-zeebe-8.1.8.jar:8.1.8]
	at io.camunda.zeebe.spring.client.ZeebeClientSpringConfiguration$1.getObject(ZeebeClientSpringConfiguration.java:35) ~[spring-zeebe-8.1.8.jar:8.1.8]
	at io.camunda.zeebe.spring.client.lifecycle.ZeebeClientLifecycle.start(ZeebeClientLifecycle.java:42) ~[spring-zeebe-8.1.8.jar:8.1.8]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-5.3.23.jar:5.3.23]
	... 14 common frames omitted
Caused by: java.net.MalformedURLException: no protocol: 'https://login.cloud.camunda.io/oauth/token'
	at java.base/java.net.URL.<init>(Unknown Source) ~[na:na]
	at java.base/java.net.URL.<init>(Unknown Source) ~[na:na]
	at java.base/java.net.URL.<init>(Unknown Source) ~[na:na]
	at io.camunda.zeebe.client.impl.oauth.OAuthCredentialsProviderBuilder.validate(OAuthCredentialsProviderBuilder.java:228) ~[zeebe-client-java-8.1.4.jar:8.1.4]
	... 22 common frames omitted
```

**Comment by korthout** [comment]
🤯 Immediately after reporting this, I discover that I can download the Spring Boot file and use the properties directly as environment variables 😅
