### ISSUE TITLE
[Bug] Failed to serialize OffsetDateTime

### ISSUE THREAD

**Issue by Oleksiivanov** [camunda-community-hub/spring-zeebe#293]
**Describe the bug**

When zeebe tries to serialize an object with [OffsetDateTime](https://docs.oracle.com/javase/8/docs/api/java/time/OffsetDateTime.html) ObjectMapper throw exception : 
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.OffsetDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: java.util.HashMap["result"]->com.microsoft.graph.models.ChatMessage["createdDateTime"])
```

**Steps to reproduce**

1. Create a new BPMN diagram with Microsoft Teams connector template.
2. Choose Conversation type `chat` , and Method `Send message to chat` in section `operation`
3. Fill required fields
4. Deploy diagram and start instance 
5. in `operate` we can see error : 

<details><summary>Click for see Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: io.camunda.zeebe.client.api.command.InternalClientException: Failed to serialize object '{result=com.microsoft.graph.models.ChatMessage@5063940a}' to json
	at io.camunda.zeebe.spring.client.jobhandling.SpringConnectorJobHandler.failJob(SpringConnectorJobHandler.java:37)
	at io.camunda.connector.runtime.util.outbound.ConnectorJobHandler.handle(ConnectorJobHandler.java:94)
	at io.camunda.zeebe.spring.client.jobhandling.SpringConnectorJobHandler.handle(SpringConnectorJobHandler.java:30)
	at io.camunda.zeebe.spring.client.jobhandling.JobHandlerInvokingSpringBeans.handle(JobHandlerInvokingSpringBeans.java:76)
	at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44)
	at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.camunda.zeebe.client.api.command.InternalClientException: Failed to serialize object '{result=com.microsoft.graph.models.ChatMessage@5063940a}' to json
	at io.camunda.zeebe.client.impl.ZeebeObjectMapper.toJson(ZeebeObjectMapper.java:83)
	at io.camunda.zeebe.client.impl.command.CommandWithVariables.variables(CommandWithVariables.java:47)
	at io.camunda.zeebe.client.impl.command.CompleteJobCommandImpl.variables(CompleteJobCommandImpl.java:34)
	at io.camunda.zeebe.spring.client.jobhandling.JobHandlerInvokingSpringBeans.createCompleteCommand(JobHandlerInvokingSpringBeans.java:165)
	at io.camunda.zeebe.spring.client.jobhandling.SpringConnectorJobHandler.completeJob(SpringConnectorJobHandler.java:54)
	at io.camunda.connector.runtime.util.outbound.ConnectorJobHandler.lambda$handle$1(ConnectorJobHandler.java:86)
	at java.base/java.util.Optional.ifPresentOrElse(Unknown Source)
	at io.camunda.connector.runtime.util.outbound.ConnectorJobHandler.handle(ConnectorJobHandler.java:77)
	... 10 more
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.OffsetDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: java.util.HashMap["result"]->com.microsoft.graph.models.ChatMessage["createdDateTime"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1306)
	at com.fasterxml.jackson.databind.ser.impl.UnsupportedTypeSerializer.serialize(UnsupportedTypeSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:733)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:808)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:764)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4624)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3869)
	at io.camunda.zeebe.client.impl.ZeebeObjectMapper.toJson(ZeebeObjectMapper.java:80)
	... 17 more

```

</p>
</details>

https://user-images.githubusercontent.com/108869886/207141892-0a570818-2a2b-401c-a37b-5171b25bcc00.mov

**Expected behavior**

Object with OffsetDateTime must be parsed without exception

**Environment:**
- OS: [e.g. Linux] 
- environment: [int](https://bru-3.operate.ultrawombat.com/) 
- cluster: new-arch-test-2022-12-13-release

**Comment by berndruecker** [comment]
Should be fixed with latest SNAPSHOT, please re-test whenever you have time - thx!

**Comment by berndruecker** [comment]
@Oleksiivanov Can you confirm this is now fixed? Then I could close this issue :-)
