### ISSUE TITLE
Unable to subscribe messages from Kafka after adding Spring Zeebe Starter

### ISSUE THREAD

**Issue by quangtd95** [camunda-community-hub/spring-zeebe#381]
I am using docker-compose to run Camunda locally with version 8.2.0-alpha5. 

My worker was written in Java Spring Boot with Spring Cloud Stream Kafka. Initially, I set up the project with Spring Cloud Stream Kafka only, and I could publish and subscribe to messages from Kafka without any issues.

Then, I added the Spring Zeebe Starter version 8.1.17
`implementation("io.camunda:spring-zeebe-starter:8.1.17") `
to work with Camunda. After adding the `@EnableZeebeClient` annotation, I could no longer subscribe to messages from Kafka, but I was still able to handle tasks from Camunda.

To resolve this issue, I upgraded the Spring Zeebe Starter to 8.2.0-alpha2.
`implementation("io.camunda:spring-zeebe-starter:8.2.0-alpha2") `
 After upgrading, I was able to subscribe to messages from Kafka, but Zeebe throws the following error continuously:

```
2023-03-27T23:02:32.412+07:00  WARN 42008 --- [ault-executor-1] io.camunda.zeebe.client.job.poller       : Failed to activate jobs for worker Default and job type dump

io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
	at io.grpc.Status.asRuntimeException(Status.java:535) ~[grpc-api-1.49.1.jar:1.49.1]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487) ~[grpc-stub-1.49.1.jar:1.49.1]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563) ~[grpc-core-1.49.1.jar:1.49.1]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70) ~[grpc-core-1.49.1.jar:1.49.1]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744) ~[grpc-core-1.49.1.jar:1.49.1]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723) ~[grpc-core-1.49.1.jar:1.49.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.49.1.jar:1.49.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.49.1.jar:1.49.1]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 00001204000000000000037fffffff000400100000000600002000000004080000000000000f0001
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1224) ~[netty-handler-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1294) ~[netty-handler-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[netty-codec-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.90.Final.jar:4.1.90.Final]
	... 1 common frames omitted
```

### Steps to reproduce:

Create a project with:
`id("org.springframework.boot") version "3.0.5"`
`implementation("org.springframework.cloud:spring-cloud-stream") extra["springCloudVersion"] = "2022.0.1"` 
Publish and subscribe messages from Kafka.
Add the Spring Zeebe Starter implementation("io.camunda:spring-zeebe-starter:8.1.17") and @EnableZeebeClient annotation.
Try to subscribe messages from Kafka.
 ### Expected behavior:
with Spring Zeebe Starter version 8.1.17
Able to subscribe to messages from Kafka after adding Spring Zeebe Starter and @EnableZeebeClient annotation.
Able to handle tasks from Camunda.

with Spring Zeebe Starter version 8.2.0-alpha2
Able to subscribe to messages from Kafka after adding Spring Zeebe Starter and @EnableZeebeClient annotation.
Able to handle tasks from Camunda.
### Actual behavior:

Cannot subscribe to messages from Kafka after adding Spring Zeebe Starter and @EnableZeebeClient annotation with version 8.1.17.
After upgrading to version 8.2.0-alpha2, able to subscribe to messages from Kafka, but Zeebe throws the error mentioned above.
Still able to handle tasks from Camunda.
### Environment:

Docker Compose
Camunda version 8.2.0-alpha5
Spring Boot with Spring Cloud Stream Kafka
Spring Zeebe Starter 8.1.17 and 8.2.0-alpha2

**Comment by chillleader** [comment]
It's very likely the same issue as in https://github.com/camunda-community-hub/spring-zeebe/issues/382
[The fix](https://github.com/camunda-community-hub/spring-zeebe/pull/383) is on the way 🙂

**Comment by berndruecker** [comment]
Faster than light - thanks @chillleader !

**Comment by chillleader** [comment]
Should be fixed in the latest snapshot, @quangtd95 could you please confirm?

**Comment by quangtd95** [comment]
> Should be fixed in the latest snapshot, @quangtd95 could you please confirm?

the fix you applied has resolved the problem completely, and the issue is no longer occurring. Thank you for the fast fix !!!

**Comment by chillleader** [comment]
Great! Then it looks like we can close the issue 🙂
