### ISSUE TITLE
Configure self-managed cluster credentials in properties

### ISSUE THREAD

**Issue by jonathanlukas** [camunda-community-hub/spring-zeebe#443]
Currently, only the gateway address of a self-managed cluster can be configured in properties.

As Camunda Platform 8 introduced a secured zeebe gateway by default in 8.2, this configuration should be applied by default in the future.

This is only possible by using environment variables at the moment:

https://github.com/camunda-community-hub/spring-zeebe/blob/main/spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/ZeebeClientConfigurationProperties.java#L681

Here, client id and client secret are read from environment variables.

Actually, it is also required to configure an auth url (keycloak token endpoint).

This is part of the OAuthCredentialsProviderBuilder which also uses env variables to configure the auth url.

However, it could be set to the builder as well.

In the end, it should be possible to configure the whole client by using a spring boot configuration.

The required parameters are:

```
zeebe.client.broker.client-id:
zeebe.client.broker.client-secret:
zeebe.client.broker.auth-url:
```

To better align with the new principle of a unified camunda client, the properties could be renamed to:

```
camunda.client.client-id:
camunda.client.client-secret:
camunda.client.auth-url:

# These are off-topic, but should show alignment with the configuration options
camunda.client.zeebe.gateway-address:
camunda.client.operate.base-url:
camunda.client.tasklist.base-url:
...
```

**Comment by floric** [comment]
This is a pretty basic and important requirement for konsistend configuration. We found the way to configure the credentials with `ZEEBE_CLIENT_ID` and `ZEEBE_CLIENT_SECRET` only by reverse engeering the source code. I really hope this issue get's solved in the near future. These missing basic configuration properties and documentation make using Camunda 8 feel like an early Alpha non-production ready version. :(

**Comment by floric** [comment]
@jonathanlukas  do you know if the variables mentioned above are right? We like to connect an application with an authenticated instance now and are not really keen for reverse engineering to configure it correctly. :(

**Comment by jonathanlukas** [comment]
Yes, they are correct: To ease your reverse engineering, please review this line: https://github.com/camunda-community-hub/spring-zeebe/blob/main/spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/ZeebeClientConfigurationProperties.java#L690

**Comment by floric** [comment]
> Yes, they are correct: To ease your reverse engineering, please review this line: https://github.com/camunda-community-hub/spring-zeebe/blob/main/spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/ZeebeClientConfigurationProperties.java#L690

Thanks for your fast reply. Yes, I'm aware of these lines. :) I was more concerned regarding the remaining OAUTH part.

**Comment by floric** [comment]
Unfortunately no luck :(

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.camunda.zeebe.client.ZeebeClient]: Factory method 'zeebeClient' threw exception; nested exception is java.lang.NullPointerException: Cannot invoke "String.lastIndexOf(int)" because the return value of "io.camunda.zeebe.spring.client.properties.ZeebeClientConfigurationProperties$Broker.access$400(io.camunda.zeebe.spring.client.properties.ZeebeClientConfigurationProperties$Broker)" is null
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
        ... 69 more
Caused by: java.lang.NullPointerException: Cannot invoke "String.lastIndexOf(int)" because the return value of "io.camunda.zeebe.spring.client.properties.ZeebeClientConfigurationProperties$Broker.access$400(io.camunda.zeebe.spring.client.properties.ZeebeClientConfigurationProperties$Broker)" is null
        at io.camunda.zeebe.spring.client.properties.ZeebeClientConfigurationProperties.getCredentialsProvider(ZeebeClientConfigurationProperties.java:693)
        at io.camunda.zeebe.client.impl.ZeebeClientImpl.buildCallCredentials(ZeebeClientImpl.java:145)
        at io.camunda.zeebe.client.impl.ZeebeClientImpl.buildGatewayStub(ZeebeClientImpl.java:184)
        at io.camunda.zeebe.spring.client.configuration.ZeebeClientProdAutoConfiguration.zeebeClient(ZeebeClientProdAutoConfiguration.java:53)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 70 more
```

I currently have the following config:

```
ZEEBE_CLIENT_ID: my-client
ZEEBE_CLIENT_SECRET: abc
OAUTH_ENV_AUTHORIZATION_SERVER: https://my-instance/realms/my-realm
```

```
zeebe:
  client:
    broker:
      # k8s internal service
      gateway-address: http://camunda-platform-zeebe-gateway
    security:
      plaintext: false
```

It seems as if still the cloud branch is taken leading to the exception.

**Comment by jonathanlukas** [comment]
Alright. The only thing you should care about is that you do not use the zeebe.client.cloud.clientId and clientSecret but only the env variables

**Comment by floric** [comment]
> Alright. The only thing you should care about is that you do not use the zeebe.client.cloud.clientId and clientSecret but only the env variables

I don't :D That's why I'm so surprised to receive this error. I checked the whole configuration.

**Comment by jonathanlukas** [comment]
Could you remove the `http://` part from your gateway-address? The used protocol is controlled by plaintext. Can you debug into the method `getCredentialsProvider()` and check whether your configuration is applied correctly?

**Comment by floric** [comment]
Ah, the error was caused by a different scope where I accidently applied the zeebe client config. Setting it directly changed the error to the `http` issue mentioned by you.
Now I have an error about a missing audience. I'm confident I can solve it. I will try to sum up the successful configuration here and hope the docs will be updated accordingly for others in the future.

**Comment by jonathanlukas** [comment]
@rbcb-bedag any chance this could become a PR? Not the BeanPostProcessor obviously but the rest.
