### ISSUE TITLE
start error in zeebe client 8.3.*

### ISSUE THREAD

**Issue by zxuanhong** [camunda-community-hub/spring-zeebe#453]
1. start error in zeebe client 8.3.*
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'zeebeClient' defined in class path resource [io/camunda/zeebe/spring/client/configuration/ZeebeClientProdAutoConfiguration.class]: Failed to instantiate [io.camunda.zeebe.client.ZeebeClient]: Factory method 'zeebeClient' threw exception with message: Receiver class io.camunda.zeebe.spring.client.properties.ZeebeClientConfigurationProperties does not define or inherit an implementation of the resolved method 'abstract int getMaxMessageSize()' of interface io.camunda.zeebe.client.ZeebeClientConfiguration.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:659) ~[spring-beans-6.0.10.jar:6.0.10]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:493) ~[spring-beans-6.0.10.jar:6.0.10]

```

2. Can you do compatible. The getMaxMessageSize() private method was added in the latest client configuration
<img width="1163" alt="image" src="https://github.com/camunda-community-hub/spring-zeebe/assets/62740686/b323b0e5-ce73-4a09-b525-adabe055e9c2">

**Comment by berndruecker** [comment]
Thanks a lot for reporting @zxuanhong
