### ISSUE TITLE
SimpleAuthentication fails for TaskListClient 

### ISSUE THREAD

**Issue by sam0r040** [camunda-community-hub/spring-zeebe#589]
**Describe the bug**
8.3.4.5 breaks authentication for the TaskListClient. 

There was an effort in https://github.com/camunda-community-hub/spring-zeebe/pull/585 to support multiple Set-Cookie with SimpleAuthentication. Unfortunately, only the OPERATE-SESSION cookie was hardcoded and therefore the TASKLIST-SESSION cookie leads to an exception. 

Example Header (Camunda 8.4, but should be the same for 8.3.x): 
`Set-Cookie: TASKLIST-SESSION=F9CEDB6C7004B88170440DFD0D8D2515; Path=/; HttpOnly; SameSite=Lax`

**To Reproduce**
Try to connect a TaskListClient with SimpleAuthentication to Camunda.  

**Expected behavior**

SimpleAuthentication should work with TaskListClient

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
Caused by: java.lang.RuntimeException: Unable to authenticate
	at io.camunda.common.auth.SimpleAuthentication.retrieveToken(SimpleAuthentication.java:73) ~[java-common-8.3.4.5.jar:8.3.4.5]
	at io.camunda.common.auth.SimpleAuthentication.getTokenHeader(SimpleAuthentication.java:86) ~[java-common-8.3.4.5.jar:8.3.4.5]
	at io.camunda.tasklist.CamundaTaskListClient.authenticate(CamundaTaskListClient.java:482) ~[camunda-tasklist-client-java-8.3.3.3.jar:na]
	at io.camunda.tasklist.CamundaTaskListClient.<init>(CamundaTaskListClient.java:61) ~[camunda-tasklist-client-java-8.3.3.3.jar:na]
	at io.camunda.tasklist.CamundaTaskListClientBuilder.build(CamundaTaskListClientBuilder.java:36) ~[camunda-tasklist-client-java-8.3.3.3.jar:na]
	at <...>(CamundaTaskListConfiguration.kt:37) ~[main/:na]
	at <...>$$SpringCGLIB$$0.CGLIB$camundaTaskListClient$0(<generated>) ~[main/:na]
	at <...>$$SpringCGLIB$$FastClass$$1.invoke(<generated>) ~[main/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[spring-core-6.1.2.jar:6.1.2]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-6.1.2.jar:6.1.2]
	at <...>$$SpringCGLIB$$0.camundaTaskListClient(<generated>) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:140) ~[spring-beans-6.1.2.jar:6.1.2]
	... 62 common frames omitted
Caused by: java.lang.RuntimeException: Unable to authenticate due to missing Set-Cookie
	at io.camunda.common.auth.SimpleAuthentication.retrieveToken(SimpleAuthentication.java:68) ~[java-common-8.3.4.5.jar:8.3.4.5]
	... 77 common frames omitted
```
Note: application packages have been redacted with <...>

</p>
</details>

**Environment:**
- OS: Linux
- Deployment: SM/docker compose
- Spring-Zeebe Version: 8.3.4.5
- SpringBoot Version: 3.2.1
- Configuration: should be default docker-compose (if it matters)

**Comment by 1nb0und** [comment]
> **Describe the bug** 8.3.4.5 breaks authentication for the TaskListClient.
> 
> There was an effort in #585 to support multiple Set-Cookie with SimpleAuthentication. Unfortunately, only the OPERATE-SESSION cookie was hardcoded and therefore the TASKLIST-SESSION cookie leads to an exception.
> 
> Example Header (Camunda 8.4, but should be the same for 8.3.x): `Set-Cookie: TASKLIST-SESSION=F9CEDB6C7004B88170440DFD0D8D2515; Path=/; HttpOnly; SameSite=Lax`
> 
> **To Reproduce** Try to connect a TaskListClient with SimpleAuthentication to Camunda.
> 
> **Expected behavior**
> 
> SimpleAuthentication should work with TaskListClient
> 
> **Log/Stacktrace**
> 
> Full Stacktrace
> **Environment:**
> 
> * OS: Linux
> * Deployment: SM/docker compose
> * Spring-Zeebe Version: 8.3.4.5
> * SpringBoot Version: 3.2.1
> * Configuration: should be default docker-compose (if it matters)

Thanks for raising this up! TaskList client will be part of this SDK and that will fix this bug.

**Comment by sam0r040** [comment]
Thanks a lot for taking care so quickly!

**Comment by 1nb0und** [comment]
@sam0r040 
The fix has been rolle out in this versions. Let us know and we can reopen this issue!

- 8.3.4.8
- 8.4.0-rc3

**Comment by sam0r040** [comment]
@1nb0und It worked in 8.3.4.8, but it looks like the fix did not make it into the 8.4.0:  https://github.com/camunda-community-hub/spring-zeebe/blob/a711d07daaf4e30d6e78b59ba9648acf9b66ac95/camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SimpleAuthentication.java#L57C17-L57C17 

It would be great if you could publish a bugfix for the 8.4.x, too?

**Comment by 1nb0und** [comment]
@sam0r040 

Good catct! I miss it. The [fix](https://github.com/camunda-community-hub/spring-zeebe/commit/31565a5ac169aab1021568107d970b92f93cd828) has been made on 8.4.x and I will publish a bug fix soon

**Comment by sam0r040** [comment]
@1nb0und Any news on the bug fix release?

**Comment by akeller** [comment]
@sam0r040 this should be part of an upcoming release this week or next.
