### ISSUE TITLE
[8.5.1] Token not refreshed

### ISSUE THREAD

**Issue by stephanpelikan** [camunda-community-hub/spring-zeebe#755]
### The problem:

After 5 Minutes the Zeebe token is not refreshed (full log attached):

```
2024-04-14T11:46:07.664+02:00  WARN 8959 --- [ault-executor-4] io.camunda.zeebe.client.job.poller       : Failed to activate jobs for worker demoService#foo and job type foo

io.grpc.StatusRuntimeException: UNAUTHENTICATED: Failed to parse bearer token, see cause for details
	at io.grpc.Status.asRuntimeException(Status.java:537) ~[grpc-api-1.60.1.jar:1.60.1]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481) ~[grpc-stub-1.60.1.jar:1.60.1]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574) ~[grpc-core-1.60.1.jar:1.60.1]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72) ~[grpc-core-1.60.1.jar:1.60.1]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742) ~[grpc-core-1.60.1.jar:1.60.1]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723) ~[grpc-core-1.60.1.jar:1.60.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.60.1.jar:1.60.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.60.1.jar:1.60.1]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
```
### How to reproduce:

1. Install camunda-platform 8.4.2 having adopted `.env` file
    ```
    ZEEBE_AUTHENTICATION_MODE=identity
    ZEEBE_CLIENT_ID=zeebe
    ZEEBE_CLIENT_SECRET=zecret
    ```
    (Don't know whether this has an effect on this issue, just for the sake of completeness)
2. Unzip demo-application (see attachment)
3. Run application and wait 5 Minutes:
    ```
    mvn package
    java -jar target/token-not-refreshed-0.0.1-SNAPSHOT.jar
    ```

### Additional question:

If an application which disables @JobWorker like this

```yaml
camunda:
  client:
    zeebe:
      defaults:
        enabled: false
```

the token should also be refreshed - once that bug I reported is fixed. Am I right?

### Files

[token_not_refreshed_log.txt](https://github.com/camunda-community-hub/spring-zeebe/files/14970191/token_not_refreshed_log.txt)
[token_not_refreshed.zip](https://github.com/camunda-community-hub/spring-zeebe/files/14970192/token_not_refreshed.zip)

**Comment by stephanpelikan** [comment]
*By-the-way:* This also happens using `spring-client-zeebe:8.3.4.2`. I don't known whether it also happens using 8.4.x since we want to upgrade straight to 8.5.0 once available and that bug is fixed.

**Comment by jonathanlukas** [comment]
Hello @stephanpelikan, could you please verify that the issue is fixed in 8.5.1?

**Comment by stephanpelikan** [comment]
Using the `token_not_refreshed` project provided above and changing to

```xml
    <dependency>
      <groupId>io.camunda.spring</groupId>
      <artifactId>spring-boot-starter-camunda</artifactId>
      <version>8.5.1</version>
    </dependency>
```

the error is *NOT* gone 😞 . Can you reproduce the problem based on the `token_not_refreshed` project?

**Comment by jonathanlukas** [comment]
@stephanpelikan thank you for your verification. I will fix this tomorrow.

**Comment by jonathanlukas** [comment]
@stephanpelikan I was not directly able to reproduce, but I found the problem. Will be fixed today.

**Comment by stephanpelikan** [comment]
@jonathanlukas : After upgrading to 8.5.2 I could run the demo-application more than 5 minutes without experiencing this error. I also tested it using my real-life application: starting, doing some action, waiting 10 minutes, doing some action. I also worked.

Thank you for your support! 😄
