### ISSUE TITLE
Multiple Set-Cookie headers in 8.4 (possibly later versions too)

### ISSUE THREAD

**Issue by jessesimpson36** [camunda-community-hub/spring-zeebe#928]
**Describe the bug**

As I was deploying the docker-compose-core.yaml file inside the camunda/camunda-platform repo, I found that newer versions of connectors in version 8.4 do not properly authenticate against Operate. I got the following stacktrace and followed it to this repo:

related to compose PR https://github.com/camunda/camunda-platform/pull/616

[ see stacktrace below  in dropdown ]

Opening this in wireshark, I see that the request/response does indeed duplicate this header:

```
POST /api/login HTTP/1.1
Accept-Encoding: gzip, x-gzip, deflate
Content-Length: 27
Content-Type: application/x-www-form-urlencoded; charset=ISO-8859-1
Host: operate:8080
Connection: keep-alive
User-Agent: Apache-HttpClient/5.3.1 (Java/21.0.3)

username=demo&password=demoHTTP/1.1 204 
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Set-Cookie: OPERATE-SESSION=FBC173FD0CFF08830495B4183EA1D2E9; Path=/; HttpOnly; SameSite=Lax
Set-Cookie: OPERATE-X-CSRF-TOKEN=4ce743aa-56e8-4dfd-8fea-0cb36bd95365; Path=/; HttpOnly; SameSite=Lax
OPERATE-X-CSRF-TOKEN: 08Loutg_PHxzVga7-N1dCTCIX0apTeDQlIR3iql2nPemYugN56GNjewMXR1eYzDewPBpbVbscn7PKIH9pOcVuZ8U-M6TUd44
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Security-Policy: default-src 'self'; base-uri 'self'; script-src 'self'; script-src-elem 'self' cdn.jsdelivr.net; connect-src 'self' cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' cdn.jsdelivr.net; img-src * data:; block-all-mixed-content; form-action 'self'; frame-ancestors 'none'; frame-src 'self' https:; object-src 'none'; font-src 'self' fonts.camunda.io cdn.jsdelivr.net; worker-src 'self' blob:; sandbox allow-forms allow-scripts allow-same-origin allow-popups
Date: Tue, 03 Sep 2024 18:01:09 GMT
Keep-Alive: timeout=60
Connection: keep-alive

```

**To Reproduce**

1. checkout the camunda/camunda-platform repo
2. `git checkout 90ecf1933529f6134b9929f7a84bdbc4bd9ab773` (which is based on 8.4)
3. `docker compose -f docker-compose-core.yaml up -d
4. wait for `docker compose -f docker-compose-core.yaml ps` to report healthy for everything except connectors
5. get the logs for connectors.

**Expected behavior**

**Log/Stacktrace**

[connectors.txt](https://github.com/user-attachments/files/16853013/connectors.txt)

<details><summary>Full Stacktrace</summary>
 <p>

```
2024-09-03T18:03:00.670Z ERROR 1 --- [   scheduling-1] i.c.common.auth.SimpleAuthentication     : Authenticating for OPERATE failed due to org.apache.hc.client5.http.ClientProtocolException
2024-09-03T18:03:00.670Z ERROR 1 --- [   scheduling-1] i.c.c.r.i.i.ProcessDefinitionImporter    : Failed to import process definitions

java.lang.RuntimeException: Unable to authenticate
	at io.camunda.common.auth.SimpleAuthentication.retrieveToken(SimpleAuthentication.java:61)
	at io.camunda.common.auth.SimpleAuthentication.getTokenHeader(SimpleAuthentication.java:82)
	at io.camunda.common.http.DefaultHttpClient.retrieveToken(DefaultHttpClient.java:207)
	at io.camunda.common.http.DefaultHttpClient.post(DefaultHttpClient.java:148)
	at io.camunda.operate.CamundaOperateClient.searchProcessDefinitionResults(CamundaOperateClient.java:46)
	at io.camunda.connector.runtime.inbound.importer.ProcessDefinitionSearch.query(ProcessDefinitionSearch.java:64)
	at io.camunda.connector.runtime.inbound.importer.ProcessDefinitionImporter.scheduleImport(ProcessDefinitionImporter.java:55)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124)
	at io.micrometer.observation.Observation.observe(Observation.java:499)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.hc.client5.http.ClientProtocolException: null
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:261)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:162)
	at io.camunda.common.auth.SimpleAuthentication.retrieveToken(SimpleAuthentication.java:41)
	... 19 common frames omitted
Caused by: org.apache.hc.core5.http.ProtocolException: multiple 'Set-Cookie' headers found
	at org.apache.hc.core5.http.message.HeaderGroup.getHeader(HeaderGroup.java:267)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpResponse.getHeader(CloseableHttpResponse.java:143)
	at io.camunda.common.auth.SimpleAuthentication.lambda$retrieveToken$0(SimpleAuthentication.java:49)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:247)
	... 22 common frames omitted

```

</p>
</details>

**Environment:**
- OS: Linux
- Deployment: SM  8.4  docker compose 
- Spring-Zeebe Version: 
- SpringBoot Version:  
- Configuration: 

Connectors 8.4.8
Operate 8.4.11

**Comment by jonathanlukas** [comment]
Connectors `8.4.8` is built with spring-zeebe `8.4.2`: https://github.com/camunda/connectors/blob/8.4.8/parent/pom.xml#L72

The cause is then this little line in a very old release: https://github.com/camunda-community-hub/spring-zeebe/blob/8.4.2/camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SimpleAuthentication.java#L49

Next: Connectors `8.4.11-rc1` uses spring-zeebe `8.4.7`: https://github.com/camunda/connectors/blob/8.4.11-rc1/parent/pom.xml#L72

Here, the initial issue is fixed, the Set-Cookie headers can be read. But this version of connectors would then face another issue: CSRF (which is not fixed with any spring-zeebe version).

CSRF can be disabled on the operate side until we backported https://github.com/camunda-community-hub/spring-zeebe/pull/860 to 8.4

**Comment by jonathanlukas** [comment]
Here is your PR: https://github.com/camunda-community-hub/spring-zeebe/pull/929
